### ISSUE TITLE
Add isort for Import Organization

### ISSUE THREAD

**Issue by ballPointPenguin** [ballPointPenguin/artificial-u#47]
## Objective

Implement isort to automatically organize and format import statements consistently across the codebase.

## Background

Well-organized imports improve code readability and maintainability. Manually organizing imports is time-consuming and prone to inconsistencies. isort automatically sorts imports according to PEP 8 guidelines, grouping them by type and alphabetizing within groups.

## Tasks

- [ ] Add isort to development dependencies in requirements-dev.txt
- [ ] Configure isort in pyproject.toml
- [ ] Ensure compatibility with Black formatting
- [ ] Apply isort to existing codebase
- [ ] Document usage in docs/development.md
- [ ] Consider adding to pre-commit hooks

## Configuration Recommendation

Add this to pyproject.toml:

```toml
[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".git", "venv", ".venv", ".mypy_cache", "__pycache__"]
known_first_party = ["artificial_u"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
```

## Command-line Usage Examples

```bash
# Sort imports in all Python files
isort .

# Check if imports are properly sorted without modifying files
isort --check-only .

# Apply isort to a specific file
isort artificial_u/models/core.py

# Show what changes would be made without modifying files
isort --diff .
```

## Acceptance Criteria

- All Python files have consistently formatted imports
- isort configuration is compatible with Black
- Clear documentation exists for running isort
- Import statements follow a logical, consistent order
- Editor/IDE integration is documented

## Technical Notes

- The "black" profile ensures compatibility with Black formatter
- Setting "known_first_party" correctly helps isort recognize project-specific modules
- isort pairs well with other linting tools like flake8 and Black
- The sections configuration determines the ordering of different import types
- Consider integrating with CI/CD to ensure all code follows the import standard
