### ISSUE TITLE
Set Up GitHub Actions CI Pipeline for pytest

### ISSUE THREAD

**Issue by ballPointPenguin** [ballPointPenguin/artificial-u#48]
## Objective

Implement a GitHub Actions CI pipeline to automatically run pytest on pull requests and commits to main branches.

## Background

Automated testing is essential for maintaining code quality and catching regressions early. GitHub Actions provides a convenient way to run tests on every code change, ensuring that only code that passes tests gets merged.

## Tasks

- [ ] Create .github/workflows/test.yml configuration file
- [ ] Configure test matrix for multiple Python versions (3.9, 3.10, 3.11)
- [ ] Set up PostgreSQL service container for integration tests
- [ ] Configure test stages (unit, integration, e2e)
- [ ] Add test coverage reporting
- [ ] Set up caching for pip dependencies to speed up workflows
- [ ] Configure workflow to run on pull requests and pushes to main
- [ ] Add status badge to README.md

## Configuration Example

```yaml
name: Python Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run tests
      env:
        TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      run: |
        pytest tests/unit/
        pytest tests/integration/
        
    - name: Generate coverage report
      run: |
        pytest --cov=artificial_u --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
```

## Acceptance Criteria

- CI pipeline successfully runs on all PRs and commits to main
- Tests run against multiple Python versions
- Integration tests run with PostgreSQL
- Test failures block PR merges
- Coverage reports are generated and visible
- Pipeline runs in a reasonable amount of time

## Technical Notes

- Consider splitting long-running tests into separate jobs
- Use appropriate test markers to categorize tests (unit, integration, e2e)
- Make sure sensitive data (API keys, etc.) is handled securely using GitHub secrets
- Add appropriate comments in workflow file for future developers
- Set reasonable timeout limits for test jobs
- Consider setting up notifications for test failures
