### ISSUE TITLE
Implement Modern Dependency Management

### ISSUE THREAD

**Issue by ballPointPenguin** [ballPointPenguin/artificial-u#49]
## Objective

Implement a modern dependency management approach to better manage package versions, development dependencies, and environment reproducibility.

## Background

The project currently uses a basic requirements.txt file for dependency management. Modern Python projects benefit from more sophisticated dependency management with features like development vs. production dependencies, lockfiles, and clearer version specifications.

## Options

We have three main approaches to consider:

### Option 1: pip-tools

**Pros:**
- Lightweight solution that builds on pip
- Generates lockfiles for reproducible installs
- Separates input requirements from resolved dependencies
- Good compatibility with existing tools
- Simple learning curve

**Cons:**
- Less full-featured than Poetry
- Requires additional setup for dev vs. prod dependencies

### Option 2: Poetry

**Pros:**
- All-in-one solution (dependency management, building, publishing)
- Sophisticated dependency resolver
- Virtual environment management built-in
- Standardized pyproject.toml configuration
- Development and production dependencies clearly separated
- Lockfile for reproducible environments

**Cons:**
- Higher learning curve
- More opinionated about project structure
- Some compatibility challenges with certain CI setups

### Option 3: Enhanced pip with pyproject.toml

**Pros:**
- Most compatible with existing tooling
- Uses the standard pyproject.toml format
- Minimal changes to workflow
- No new tools to learn

**Cons:**
- Limited features compared to Poetry or pip-tools
- No lockfile by default
- Manual management of dev vs. prod dependencies

## Tasks

- [ ] Evaluate and select a dependency management approach
- [ ] Create initial configuration (pip-tools, Poetry, or pyproject.toml)
- [ ] Migrate current dependencies from requirements.txt
- [ ] Separate development dependencies
- [ ] Generate lockfile for reproducible builds
- [ ] Update documentation with new workflow instructions
- [ ] Update CI/CD configuration to use the new approach

### Poetry Configuration
```toml
[tool.poetry]
name = "artificial-u"
version = "0.1.0"
description = "AI-powered educational content platform"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
license = "AGPL-3.0-or-later"
packages = [{include = "artificial_u"}]

[tool.poetry.dependencies]
python = "^3.9"
alembic = "^1.12.0"
anthropic = "^0.18.1"
click = "^8.1.7"
elevenlabs = "^0.2.24"
fastapi = "^0.115.0"
httpx = "^0.28.0"
psycopg2-binary = "^2.9.0"
pydantic-settings = "^2.8.0"
pydantic = "^2.11.3"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
rich = "^13.6.0"
sqlalchemy = "^2.0.23"
uvicorn = {extras = ["standard"], version = "^0.34.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-cov = "^4.0.0"
pytest-env = "^1.0.0"
black = "^23.1.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
pre-commit = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### pip-tools Configuration
requirements.in:
```
alembic>=1.12.0
anthropic>=0.18.1
click>=8.1.7
elevenlabs>=0.2.24
fastapi>=0.115.0
httpx>=0.28.0
psycopg2-binary>=2.9.0
pydantic-settings>=2.8.0
pydantic>=2.11.3
python-dotenv>=1.0.0
python-multipart>=0.0.6
rich>=13.6.0
sqlalchemy>=2.0.23
uvicorn[standard]>=0.34.0
```

requirements-dev.in:
```
-r requirements.in
pytest>=7.0.0
pytest-cov>=4.0.0
pytest-env>=1.0.0
black>=23.1.0
isort>=5.12.0
flake8>=6.0.0
mypy>=1.0.0
pre-commit>=3.0.0
```

## Acceptance Criteria

- Selected approach is implemented and working
- Development dependencies are separated from production
- Lockfile is generated for reproducible builds
- CI/CD pipeline is updated to use the new approach
- Documentation is updated with new workflow instructions
- Team members can successfully install dependencies

## Technical Notes

- Consider compatibility with existing tools and workflows
- Minimize learning curve for the team
- Consider CI/CD integration requirements
- Evaluate impact on build and deployment processes
- Consider long-term maintenance implications
