### ISSUE TITLE
Create Basic pyproject.toml Configuration

### ISSUE THREAD

**Issue by ballPointPenguin** [ballPointPenguin/artificial-u#50]
## Objective

Create a standardized pyproject.toml file to centralize project configuration, enable modern Python tooling, and improve project metadata.

## Background

The Python ecosystem is moving toward standardized project configuration via pyproject.toml (PEP 518, PEP 621). This file centralizes configurations for build systems, testing tools, code formatters, and linters, reducing the need for multiple configuration files.

## Tasks

- [ ] Create initial pyproject.toml file with project metadata
- [ ] Configure build system information
- [ ] Add tool-specific configurations (pytest, black, isort, etc.)
- [ ] Ensure compatibility with existing workflow
- [ ] Document the purpose and usage of the file
- [ ] Consider adding packaging metadata for future distribution

## Configuration Example

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "artificial-u"
version = "0.1.0"
description = "AI-powered educational content platform"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "AGPL-3.0"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Education",
]
keywords = ["education", "ai", "text-to-speech", "lecture"]

[project.urls]
"Homepage" = "https://github.com/ballPointPenguin/artificial-u"
"Bug Tracker" = "https://github.com/ballPointPenguin/artificial-u/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "e2e: End-to-end tests",
]
filterwarnings = [
    "ignore::DeprecationWarning:sqlalchemy.*:",
]

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".git", "venv", ".venv", ".mypy_cache", "__pycache__"]
known_first_party = ["artificial_u"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
follow_imports = "silent"
```

## Acceptance Criteria

- pyproject.toml file is created with proper syntax
- File contains accurate project metadata
- Appropriate tool configurations are included
- File does not conflict with existing configuration files
- Documentation clarifies the purpose and benefits of the file
- Configuration works with supported tools (pytest, black, isort, etc.)

## Technical Notes

- This file is a PEP 518/621 standard for Python project metadata and build configuration
- The file can replace several tool-specific config files (.flake8, .isort.cfg, etc.)
- Consider how this file will interact with dependency management decisions (Poetry or pip-tools)
- Keep the file well-commented for future contributors
- This does not replace requirements.txt yet - that depends on the dependency management decision
- Consider using hatchling as it's a lightweight, modern builder
