### ISSUE TITLE
Implement MinIO as Local S3-Compatible Storage Solution

### ISSUE THREAD

**Issue by ballPointPenguin** [ballPointPenguin/artificial-u#52]
## Objective

Implement a local S3-compatible storage solution using MinIO for storing audio files and other content, providing a development environment that closely mirrors production S3 functionality.

## Tasks

- [ ] Add MinIO service to the Docker Compose configuration
- [ ] Configure MinIO with appropriate buckets for different content types (audio, lectures, etc.)
- [ ] Implement a storage service layer that abstracts S3/MinIO operations
- [ ] Create utility functions for file uploads, downloads, and URL generation
- [ ] Add configuration options to switch between local MinIO and production S3
- [ ] Implement proper error handling for storage operations
- [ ] Add basic security policies for bucket access
- [ ] Create documentation for local development with MinIO

### Docker Compose Configuration

```yaml
services:
  # Existing services
  
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin     # Change these in production
      MINIO_ROOT_PASSWORD: minioadmin # Change these in production
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO client for bucket setup
  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/artificial-u-audio;
      /usr/bin/mc mb myminio/artificial-u-lectures;
      /usr/bin/mc policy set download myminio/artificial-u-audio;
      exit 0;
      "

volumes:
  minio_data:
```

### Storage Service Layer

Create a storage service that abstracts S3 operations and handles environment switching:

```python
# artificial_u/api/services/storage_service.py
import boto3
from botocore.client import Config
import os
from typing import BinaryIO, Optional, Tuple

from artificial_u.api.config import settings


class StorageService:
    """Service for handling file storage operations with S3/MinIO compatibility"""
    
    def __init__(self):
        """Initialize the storage service with appropriate client"""
        self.client = self._get_s3_client()
        self.audio_bucket = settings.STORAGE_AUDIO_BUCKET
        self.lectures_bucket = settings.STORAGE_LECTURES_BUCKET
        
    def _get_s3_client(self):
        """Get appropriate S3 client based on environment"""
        # Use local MinIO in development
        if settings.ENVIRONMENT != "production":
            return boto3.client(
                's3',
                endpoint_url=settings.STORAGE_ENDPOINT_URL,
                aws_access_key_id=settings.STORAGE_ACCESS_KEY,
                aws_secret_access_key=settings.STORAGE_SECRET_KEY,
                config=Config(signature_version='s3v4'),
                region_name=settings.STORAGE_REGION
            )
        # Use real AWS S3 in production
        else:
            return boto3.client(
                's3',
                aws_access_key_id=settings.STORAGE_ACCESS_KEY,
                aws_secret_access_key=settings.STORAGE_SECRET_KEY,
                region_name=settings.STORAGE_REGION
            )
    
    async def upload_audio_file(self, file_data: bytes, object_name: str) -> Tuple[bool, Optional[str]]:
        """
        Upload audio file data to storage
        
        Args:
            file_data: Binary file data
            object_name: Object key/name
            
        Returns:
            Tuple of (success, url)
        """
        try:
            import io
            file_obj = io.BytesIO(file_data)
            
            # Upload to S3/MinIO
            self.client.upload_fileobj(
                file_obj, 
                self.audio_bucket, 
                object_name,
                ExtraArgs={'ContentType': 'audio/mpeg'}  # Adjust based on file type
            )
            
            # Generate URL
            url = self.get_file_url(self.audio_bucket, object_name)
            return True, url
        except Exception as e:
            # Log the error
            print(f"Error uploading file: {str(e)}")
            return False, None
    
    def get_file_url(self, bucket: str, object_name: str) -> str:
        """
        Generate URL for a stored file
        
        Args:
            bucket: Bucket name
            object_name: Object key/name
            
        Returns:
            Public URL for the file
        """
        if settings.ENVIRONMENT != "production":
            # Local MinIO URL
            return f"{settings.STORAGE_PUBLIC_URL}/{bucket}/{object_name}"
        else:
            # AWS S3 URL (can use presigned URLs if needed)
            return f"https://{bucket}.s3.{settings.STORAGE_REGION}.amazonaws.com/{object_name}"
    
    async def download_file(self, bucket: str, object_name: str) -> Tuple[Optional[bytes], Optional[str]]:
        """
        Download a file from storage
        
        Args:
            bucket: Bucket name
            object_name: Object key/name
            
        Returns:
            Tuple of (file_data, content_type)
        """
        try:
            import io
            file_obj = io.BytesIO()
            
            # Get content type
            response = self.client.head_object(Bucket=bucket, Key=object_name)
            content_type = response.get('ContentType', 'application/octet-stream')
            
            # Download file
            self.client.download_fileobj(bucket, object_name, file_obj)
            file_obj.seek(0)
            
            return file_obj.read(), content_type
        except Exception as e:
            # Log the error
            print(f"Error downloading file: {str(e)}")
            return None, None
    
    async def delete_file(self, bucket: str, object_name: str) -> bool:
        """
        Delete a file from storage
        
        Args:
            bucket: Bucket name
            object_name: Object key/name
            
        Returns:
            Success flag
        """
        try:
            self.client.delete_object(Bucket=bucket, Key=object_name)
            return True
        except Exception as e:
            # Log the error
            print(f"Error deleting file: {str(e)}")
            return False
```

### Configuration Settings

Add the following to your configuration settings:

```python
# In config.py or settings.py
class Settings(BaseSettings):
    # Existing settings
    
    # Storage settings
    STORAGE_TYPE: str = "minio"  # "minio" or "s3"
    STORAGE_ENDPOINT_URL: str = "http://minio:9000"  # For MinIO in Docker network
    STORAGE_PUBLIC_URL: str = "http://localhost:9000"  # For public access URLs
    STORAGE_ACCESS_KEY: str = "minioadmin"
    STORAGE_SECRET_KEY: str = "minioadmin"
    STORAGE_REGION: str = "us-east-1"
    STORAGE_AUDIO_BUCKET: str = "artificial-u-audio"
    STORAGE_LECTURES_BUCKET: str = "artificial-u-lectures"
```

## Integration with API

The storage service would be integrated with the API endpoints for audio and lecture resources:

1. **Audio Upload**: When audio is generated or uploaded, store it in MinIO/S3
2. **Audio Download**: Stream file from storage when requested
3. **Lecture Content**: Store and retrieve lecture content files if needed

## Success Criteria

- MinIO runs successfully in Docker environment
- Storage service properly abstracts S3/MinIO operations
- Files can be uploaded, downloaded, and deleted through the service
- Public URLs work correctly for serving content
- Configuration allows seamless switching between development and production
- Integration with API endpoints works correctly

## Technical Notes

- MinIO provides an almost identical API to AWS S3, allowing for easy transition
- Use boto3 for consistent interface between local and production environments
- Consider implementing caching for frequently accessed files
- Add proper error handling and retry logic
- Set up appropriate bucket policies for public vs. private content
- In production, consider using CloudFront or similar CDN for better performance
- Consider implementing file validation before storage
- Add support for different content types and metadata
